/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using spanclient.Client;
using spanclient.Api;
using spanclient.Model;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing DatadumpApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DatadumpApiTests : IDisposable
    {
        private DatadumpApi instance;

        public DatadumpApiTests()
        {
            instance = new DatadumpApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DatadumpApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DatadumpApi
            //Assert.IsType(typeof(DatadumpApi), instance, "instance is a DatadumpApi");
        }

        
        /// <summary>
        /// Test DataDump
        /// </summary>
        [Fact]
        public void DataDumpTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object body = null;
            //var response = instance.DataDump(body);
            //Assert.IsType<DataDumpResponse> (response, "response is DataDumpResponse");
        }
        
    }

}
