/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.0.12 reported-davon
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using spanclient.Client;
using spanclient.Model;

namespace spanclient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICollectionsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Broadcast message
        /// </summary>
        /// <remarks>
        /// Broadcast a message to all devices in the collection. This request will always succeed if the collection exists, even if there are one or more send errors. Individual errors are returned as an array of error messages in the response. Use equivalent to resource for devices to send a message to single device.
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="body"></param>
        /// <returns>MultiSendMessageResponse</returns>
        MultiSendMessageResponse BroadcastMessage (string collectionId, SendMessageRequest body);

        /// <summary>
        /// Broadcast message
        /// </summary>
        /// <remarks>
        /// Broadcast a message to all devices in the collection. This request will always succeed if the collection exists, even if there are one or more send errors. Individual errors are returned as an array of error messages in the response. Use equivalent to resource for devices to send a message to single device.
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="body"></param>
        /// <returns>ApiResponse of MultiSendMessageResponse</returns>
        ApiResponse<MultiSendMessageResponse> BroadcastMessageWithHttpInfo (string collectionId, SendMessageRequest body);
        /// <summary>
        /// Create collection
        /// </summary>
        /// <remarks>
        /// The returned collection is the collection stored in the backend. Defaults have been set. There are no required fields in a collection
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Collection</returns>
        Collection CreateCollection (Collection body);

        /// <summary>
        /// Create collection
        /// </summary>
        /// <remarks>
        /// The returned collection is the collection stored in the backend. Defaults have been set. There are no required fields in a collection
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of Collection</returns>
        ApiResponse<Collection> CreateCollectionWithHttpInfo (Collection body);
        /// <summary>
        /// Delete collection
        /// </summary>
        /// <remarks>
        /// You must have write access to the collection
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The ID of the collection you want to delete</param>
        /// <returns>Collection</returns>
        Collection DeleteCollection (string collectionId);

        /// <summary>
        /// Delete collection
        /// </summary>
        /// <remarks>
        /// You must have write access to the collection
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The ID of the collection you want to delete</param>
        /// <returns>ApiResponse of Collection</returns>
        ApiResponse<Collection> DeleteCollectionWithHttpInfo (string collectionId);
        /// <summary>
        /// Get payloads
        /// </summary>
        /// <remarks>
        /// List the data received from all the devices in the collection.
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The collection ID requested. This is included in the request path.</param>
        /// <param name="limit">Limit the number of payloads to return. The default is 512. (optional)</param>
        /// <param name="start">Start of time range. The default is 24 hours ago. Value is in milliseconds since epoch. (optional)</param>
        /// <param name="end">End of time range. The default is the current time stamp. Value is in milliseconds since epoch. (optional)</param>
        /// <returns>ListDataResponse</returns>
        ListDataResponse ListCollectionData (string collectionId, int? limit = default(int?), string start = default(string), string end = default(string));

        /// <summary>
        /// Get payloads
        /// </summary>
        /// <remarks>
        /// List the data received from all the devices in the collection.
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The collection ID requested. This is included in the request path.</param>
        /// <param name="limit">Limit the number of payloads to return. The default is 512. (optional)</param>
        /// <param name="start">Start of time range. The default is 24 hours ago. Value is in milliseconds since epoch. (optional)</param>
        /// <param name="end">End of time range. The default is the current time stamp. Value is in milliseconds since epoch. (optional)</param>
        /// <returns>ApiResponse of ListDataResponse</returns>
        ApiResponse<ListDataResponse> ListCollectionDataWithHttpInfo (string collectionId, int? limit = default(int?), string start = default(string), string end = default(string));
        /// <summary>
        /// List collections
        /// </summary>
        /// <remarks>
        /// Lists all the collections that one of your teams owns.
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListCollectionResponse</returns>
        ListCollectionResponse ListCollections ();

        /// <summary>
        /// List collections
        /// </summary>
        /// <remarks>
        /// Lists all the collections that one of your teams owns.
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListCollectionResponse</returns>
        ApiResponse<ListCollectionResponse> ListCollectionsWithHttpInfo ();
        /// <summary>
        /// Retrieve collection
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The collection ID of the collection you are requesting</param>
        /// <returns>Collection</returns>
        Collection RetrieveCollection (string collectionId);

        /// <summary>
        /// Retrieve collection
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The collection ID of the collection you are requesting</param>
        /// <returns>ApiResponse of Collection</returns>
        ApiResponse<Collection> RetrieveCollectionWithHttpInfo (string collectionId);
        /// <summary>
        /// Update collection
        /// </summary>
        /// <remarks>
        /// You must have write access to the collection, ie. you must administer it
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The ID of the collection. This is assigned by the backend.</param>
        /// <param name="body"></param>
        /// <returns>Collection</returns>
        Collection UpdateCollection (string collectionId, Collection body);

        /// <summary>
        /// Update collection
        /// </summary>
        /// <remarks>
        /// You must have write access to the collection, ie. you must administer it
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The ID of the collection. This is assigned by the backend.</param>
        /// <param name="body"></param>
        /// <returns>ApiResponse of Collection</returns>
        ApiResponse<Collection> UpdateCollectionWithHttpInfo (string collectionId, Collection body);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICollectionsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Broadcast message
        /// </summary>
        /// <remarks>
        /// Broadcast a message to all devices in the collection. This request will always succeed if the collection exists, even if there are one or more send errors. Individual errors are returned as an array of error messages in the response. Use equivalent to resource for devices to send a message to single device.
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="body"></param>
        /// <returns>Task of MultiSendMessageResponse</returns>
        System.Threading.Tasks.Task<MultiSendMessageResponse> BroadcastMessageAsync (string collectionId, SendMessageRequest body);

        /// <summary>
        /// Broadcast message
        /// </summary>
        /// <remarks>
        /// Broadcast a message to all devices in the collection. This request will always succeed if the collection exists, even if there are one or more send errors. Individual errors are returned as an array of error messages in the response. Use equivalent to resource for devices to send a message to single device.
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (MultiSendMessageResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<MultiSendMessageResponse>> BroadcastMessageAsyncWithHttpInfo (string collectionId, SendMessageRequest body);
        /// <summary>
        /// Create collection
        /// </summary>
        /// <remarks>
        /// The returned collection is the collection stored in the backend. Defaults have been set. There are no required fields in a collection
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of Collection</returns>
        System.Threading.Tasks.Task<Collection> CreateCollectionAsync (Collection body);

        /// <summary>
        /// Create collection
        /// </summary>
        /// <remarks>
        /// The returned collection is the collection stored in the backend. Defaults have been set. There are no required fields in a collection
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (Collection)</returns>
        System.Threading.Tasks.Task<ApiResponse<Collection>> CreateCollectionAsyncWithHttpInfo (Collection body);
        /// <summary>
        /// Delete collection
        /// </summary>
        /// <remarks>
        /// You must have write access to the collection
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The ID of the collection you want to delete</param>
        /// <returns>Task of Collection</returns>
        System.Threading.Tasks.Task<Collection> DeleteCollectionAsync (string collectionId);

        /// <summary>
        /// Delete collection
        /// </summary>
        /// <remarks>
        /// You must have write access to the collection
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The ID of the collection you want to delete</param>
        /// <returns>Task of ApiResponse (Collection)</returns>
        System.Threading.Tasks.Task<ApiResponse<Collection>> DeleteCollectionAsyncWithHttpInfo (string collectionId);
        /// <summary>
        /// Get payloads
        /// </summary>
        /// <remarks>
        /// List the data received from all the devices in the collection.
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The collection ID requested. This is included in the request path.</param>
        /// <param name="limit">Limit the number of payloads to return. The default is 512. (optional)</param>
        /// <param name="start">Start of time range. The default is 24 hours ago. Value is in milliseconds since epoch. (optional)</param>
        /// <param name="end">End of time range. The default is the current time stamp. Value is in milliseconds since epoch. (optional)</param>
        /// <returns>Task of ListDataResponse</returns>
        System.Threading.Tasks.Task<ListDataResponse> ListCollectionDataAsync (string collectionId, int? limit = default(int?), string start = default(string), string end = default(string));

        /// <summary>
        /// Get payloads
        /// </summary>
        /// <remarks>
        /// List the data received from all the devices in the collection.
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The collection ID requested. This is included in the request path.</param>
        /// <param name="limit">Limit the number of payloads to return. The default is 512. (optional)</param>
        /// <param name="start">Start of time range. The default is 24 hours ago. Value is in milliseconds since epoch. (optional)</param>
        /// <param name="end">End of time range. The default is the current time stamp. Value is in milliseconds since epoch. (optional)</param>
        /// <returns>Task of ApiResponse (ListDataResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListDataResponse>> ListCollectionDataAsyncWithHttpInfo (string collectionId, int? limit = default(int?), string start = default(string), string end = default(string));
        /// <summary>
        /// List collections
        /// </summary>
        /// <remarks>
        /// Lists all the collections that one of your teams owns.
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ListCollectionResponse</returns>
        System.Threading.Tasks.Task<ListCollectionResponse> ListCollectionsAsync ();

        /// <summary>
        /// List collections
        /// </summary>
        /// <remarks>
        /// Lists all the collections that one of your teams owns.
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (ListCollectionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListCollectionResponse>> ListCollectionsAsyncWithHttpInfo ();
        /// <summary>
        /// Retrieve collection
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The collection ID of the collection you are requesting</param>
        /// <returns>Task of Collection</returns>
        System.Threading.Tasks.Task<Collection> RetrieveCollectionAsync (string collectionId);

        /// <summary>
        /// Retrieve collection
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The collection ID of the collection you are requesting</param>
        /// <returns>Task of ApiResponse (Collection)</returns>
        System.Threading.Tasks.Task<ApiResponse<Collection>> RetrieveCollectionAsyncWithHttpInfo (string collectionId);
        /// <summary>
        /// Update collection
        /// </summary>
        /// <remarks>
        /// You must have write access to the collection, ie. you must administer it
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The ID of the collection. This is assigned by the backend.</param>
        /// <param name="body"></param>
        /// <returns>Task of Collection</returns>
        System.Threading.Tasks.Task<Collection> UpdateCollectionAsync (string collectionId, Collection body);

        /// <summary>
        /// Update collection
        /// </summary>
        /// <remarks>
        /// You must have write access to the collection, ie. you must administer it
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The ID of the collection. This is assigned by the backend.</param>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (Collection)</returns>
        System.Threading.Tasks.Task<ApiResponse<Collection>> UpdateCollectionAsyncWithHttpInfo (string collectionId, Collection body);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICollectionsApi : ICollectionsApiSync, ICollectionsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CollectionsApi : ICollectionsApi
    {
        private spanclient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CollectionsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CollectionsApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CollectionsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CollectionsApi(String basePath)
        {
            this.Configuration = spanclient.Client.Configuration.MergeConfigurations(
                spanclient.Client.GlobalConfiguration.Instance,
                new spanclient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new spanclient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new spanclient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = spanclient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CollectionsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public CollectionsApi(spanclient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = spanclient.Client.Configuration.MergeConfigurations(
                spanclient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new spanclient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new spanclient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = spanclient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CollectionsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public CollectionsApi(spanclient.Client.ISynchronousClient client,spanclient.Client.IAsynchronousClient asyncClient, spanclient.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = spanclient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public spanclient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public spanclient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public spanclient.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public spanclient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Broadcast message Broadcast a message to all devices in the collection. This request will always succeed if the collection exists, even if there are one or more send errors. Individual errors are returned as an array of error messages in the response. Use equivalent to resource for devices to send a message to single device.
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="body"></param>
        /// <returns>MultiSendMessageResponse</returns>
        public MultiSendMessageResponse BroadcastMessage (string collectionId, SendMessageRequest body)
        {
             spanclient.Client.ApiResponse<MultiSendMessageResponse> localVarResponse = BroadcastMessageWithHttpInfo(collectionId, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Broadcast message Broadcast a message to all devices in the collection. This request will always succeed if the collection exists, even if there are one or more send errors. Individual errors are returned as an array of error messages in the response. Use equivalent to resource for devices to send a message to single device.
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="body"></param>
        /// <returns>ApiResponse of MultiSendMessageResponse</returns>
        public spanclient.Client.ApiResponse< MultiSendMessageResponse > BroadcastMessageWithHttpInfo (string collectionId, SendMessageRequest body)
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling CollectionsApi->BroadcastMessage");

            // verify the required parameter 'body' is set
            if (body == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'body' when calling CollectionsApi->BroadcastMessage");

            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = spanclient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = spanclient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter
            localVarRequestOptions.Data = body;

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post< MultiSendMessageResponse >("/collections/{collectionId}/to", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BroadcastMessage", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Broadcast message Broadcast a message to all devices in the collection. This request will always succeed if the collection exists, even if there are one or more send errors. Individual errors are returned as an array of error messages in the response. Use equivalent to resource for devices to send a message to single device.
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="body"></param>
        /// <returns>Task of MultiSendMessageResponse</returns>
        public async System.Threading.Tasks.Task<MultiSendMessageResponse> BroadcastMessageAsync (string collectionId, SendMessageRequest body)
        {
             spanclient.Client.ApiResponse<MultiSendMessageResponse> localVarResponse = await BroadcastMessageAsyncWithHttpInfo(collectionId, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Broadcast message Broadcast a message to all devices in the collection. This request will always succeed if the collection exists, even if there are one or more send errors. Individual errors are returned as an array of error messages in the response. Use equivalent to resource for devices to send a message to single device.
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (MultiSendMessageResponse)</returns>
        public async System.Threading.Tasks.Task<spanclient.Client.ApiResponse<MultiSendMessageResponse>> BroadcastMessageAsyncWithHttpInfo (string collectionId, SendMessageRequest body)
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling CollectionsApi->BroadcastMessage");

            // verify the required parameter 'body' is set
            if (body == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'body' when calling CollectionsApi->BroadcastMessage");


            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter
            localVarRequestOptions.Data = body;

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<MultiSendMessageResponse>("/collections/{collectionId}/to", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BroadcastMessage", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create collection The returned collection is the collection stored in the backend. Defaults have been set. There are no required fields in a collection
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Collection</returns>
        public Collection CreateCollection (Collection body)
        {
             spanclient.Client.ApiResponse<Collection> localVarResponse = CreateCollectionWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create collection The returned collection is the collection stored in the backend. Defaults have been set. There are no required fields in a collection
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of Collection</returns>
        public spanclient.Client.ApiResponse< Collection > CreateCollectionWithHttpInfo (Collection body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'body' when calling CollectionsApi->CreateCollection");

            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = spanclient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = spanclient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = body;

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post< Collection >("/collections", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateCollection", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create collection The returned collection is the collection stored in the backend. Defaults have been set. There are no required fields in a collection
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of Collection</returns>
        public async System.Threading.Tasks.Task<Collection> CreateCollectionAsync (Collection body)
        {
             spanclient.Client.ApiResponse<Collection> localVarResponse = await CreateCollectionAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create collection The returned collection is the collection stored in the backend. Defaults have been set. There are no required fields in a collection
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (Collection)</returns>
        public async System.Threading.Tasks.Task<spanclient.Client.ApiResponse<Collection>> CreateCollectionAsyncWithHttpInfo (Collection body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'body' when calling CollectionsApi->CreateCollection");


            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            localVarRequestOptions.Data = body;

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Collection>("/collections", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateCollection", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete collection You must have write access to the collection
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The ID of the collection you want to delete</param>
        /// <returns>Collection</returns>
        public Collection DeleteCollection (string collectionId)
        {
             spanclient.Client.ApiResponse<Collection> localVarResponse = DeleteCollectionWithHttpInfo(collectionId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Delete collection You must have write access to the collection
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The ID of the collection you want to delete</param>
        /// <returns>ApiResponse of Collection</returns>
        public spanclient.Client.ApiResponse< Collection > DeleteCollectionWithHttpInfo (string collectionId)
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling CollectionsApi->DeleteCollection");

            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = spanclient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = spanclient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete< Collection >("/collections/{collectionId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteCollection", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete collection You must have write access to the collection
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The ID of the collection you want to delete</param>
        /// <returns>Task of Collection</returns>
        public async System.Threading.Tasks.Task<Collection> DeleteCollectionAsync (string collectionId)
        {
             spanclient.Client.ApiResponse<Collection> localVarResponse = await DeleteCollectionAsyncWithHttpInfo(collectionId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Delete collection You must have write access to the collection
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The ID of the collection you want to delete</param>
        /// <returns>Task of ApiResponse (Collection)</returns>
        public async System.Threading.Tasks.Task<spanclient.Client.ApiResponse<Collection>> DeleteCollectionAsyncWithHttpInfo (string collectionId)
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling CollectionsApi->DeleteCollection");


            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Collection>("/collections/{collectionId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteCollection", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get payloads List the data received from all the devices in the collection.
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The collection ID requested. This is included in the request path.</param>
        /// <param name="limit">Limit the number of payloads to return. The default is 512. (optional)</param>
        /// <param name="start">Start of time range. The default is 24 hours ago. Value is in milliseconds since epoch. (optional)</param>
        /// <param name="end">End of time range. The default is the current time stamp. Value is in milliseconds since epoch. (optional)</param>
        /// <returns>ListDataResponse</returns>
        public ListDataResponse ListCollectionData (string collectionId, int? limit = default(int?), string start = default(string), string end = default(string))
        {
             spanclient.Client.ApiResponse<ListDataResponse> localVarResponse = ListCollectionDataWithHttpInfo(collectionId, limit, start, end);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get payloads List the data received from all the devices in the collection.
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The collection ID requested. This is included in the request path.</param>
        /// <param name="limit">Limit the number of payloads to return. The default is 512. (optional)</param>
        /// <param name="start">Start of time range. The default is 24 hours ago. Value is in milliseconds since epoch. (optional)</param>
        /// <param name="end">End of time range. The default is the current time stamp. Value is in milliseconds since epoch. (optional)</param>
        /// <returns>ApiResponse of ListDataResponse</returns>
        public spanclient.Client.ApiResponse< ListDataResponse > ListCollectionDataWithHttpInfo (string collectionId, int? limit = default(int?), string start = default(string), string end = default(string))
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling CollectionsApi->ListCollectionData");

            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = spanclient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = spanclient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(spanclient.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (start != null)
            {
                localVarRequestOptions.QueryParameters.Add(spanclient.Client.ClientUtils.ParameterToMultiMap("", "start", start));
            }
            if (end != null)
            {
                localVarRequestOptions.QueryParameters.Add(spanclient.Client.ClientUtils.ParameterToMultiMap("", "end", end));
            }

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get< ListDataResponse >("/collections/{collectionId}/data", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListCollectionData", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get payloads List the data received from all the devices in the collection.
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The collection ID requested. This is included in the request path.</param>
        /// <param name="limit">Limit the number of payloads to return. The default is 512. (optional)</param>
        /// <param name="start">Start of time range. The default is 24 hours ago. Value is in milliseconds since epoch. (optional)</param>
        /// <param name="end">End of time range. The default is the current time stamp. Value is in milliseconds since epoch. (optional)</param>
        /// <returns>Task of ListDataResponse</returns>
        public async System.Threading.Tasks.Task<ListDataResponse> ListCollectionDataAsync (string collectionId, int? limit = default(int?), string start = default(string), string end = default(string))
        {
             spanclient.Client.ApiResponse<ListDataResponse> localVarResponse = await ListCollectionDataAsyncWithHttpInfo(collectionId, limit, start, end);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get payloads List the data received from all the devices in the collection.
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The collection ID requested. This is included in the request path.</param>
        /// <param name="limit">Limit the number of payloads to return. The default is 512. (optional)</param>
        /// <param name="start">Start of time range. The default is 24 hours ago. Value is in milliseconds since epoch. (optional)</param>
        /// <param name="end">End of time range. The default is the current time stamp. Value is in milliseconds since epoch. (optional)</param>
        /// <returns>Task of ApiResponse (ListDataResponse)</returns>
        public async System.Threading.Tasks.Task<spanclient.Client.ApiResponse<ListDataResponse>> ListCollectionDataAsyncWithHttpInfo (string collectionId, int? limit = default(int?), string start = default(string), string end = default(string))
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling CollectionsApi->ListCollectionData");


            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(spanclient.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (start != null)
            {
                localVarRequestOptions.QueryParameters.Add(spanclient.Client.ClientUtils.ParameterToMultiMap("", "start", start));
            }
            if (end != null)
            {
                localVarRequestOptions.QueryParameters.Add(spanclient.Client.ClientUtils.ParameterToMultiMap("", "end", end));
            }

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListDataResponse>("/collections/{collectionId}/data", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListCollectionData", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List collections Lists all the collections that one of your teams owns.
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListCollectionResponse</returns>
        public ListCollectionResponse ListCollections ()
        {
             spanclient.Client.ApiResponse<ListCollectionResponse> localVarResponse = ListCollectionsWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// List collections Lists all the collections that one of your teams owns.
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListCollectionResponse</returns>
        public spanclient.Client.ApiResponse< ListCollectionResponse > ListCollectionsWithHttpInfo ()
        {
            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = spanclient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = spanclient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get< ListCollectionResponse >("/collections", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListCollections", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List collections Lists all the collections that one of your teams owns.
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ListCollectionResponse</returns>
        public async System.Threading.Tasks.Task<ListCollectionResponse> ListCollectionsAsync ()
        {
             spanclient.Client.ApiResponse<ListCollectionResponse> localVarResponse = await ListCollectionsAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// List collections Lists all the collections that one of your teams owns.
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (ListCollectionResponse)</returns>
        public async System.Threading.Tasks.Task<spanclient.Client.ApiResponse<ListCollectionResponse>> ListCollectionsAsyncWithHttpInfo ()
        {

            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListCollectionResponse>("/collections", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListCollections", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve collection 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The collection ID of the collection you are requesting</param>
        /// <returns>Collection</returns>
        public Collection RetrieveCollection (string collectionId)
        {
             spanclient.Client.ApiResponse<Collection> localVarResponse = RetrieveCollectionWithHttpInfo(collectionId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve collection 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The collection ID of the collection you are requesting</param>
        /// <returns>ApiResponse of Collection</returns>
        public spanclient.Client.ApiResponse< Collection > RetrieveCollectionWithHttpInfo (string collectionId)
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling CollectionsApi->RetrieveCollection");

            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = spanclient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = spanclient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get< Collection >("/collections/{collectionId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RetrieveCollection", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve collection 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The collection ID of the collection you are requesting</param>
        /// <returns>Task of Collection</returns>
        public async System.Threading.Tasks.Task<Collection> RetrieveCollectionAsync (string collectionId)
        {
             spanclient.Client.ApiResponse<Collection> localVarResponse = await RetrieveCollectionAsyncWithHttpInfo(collectionId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieve collection 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The collection ID of the collection you are requesting</param>
        /// <returns>Task of ApiResponse (Collection)</returns>
        public async System.Threading.Tasks.Task<spanclient.Client.ApiResponse<Collection>> RetrieveCollectionAsyncWithHttpInfo (string collectionId)
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling CollectionsApi->RetrieveCollection");


            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Collection>("/collections/{collectionId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RetrieveCollection", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update collection You must have write access to the collection, ie. you must administer it
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The ID of the collection. This is assigned by the backend.</param>
        /// <param name="body"></param>
        /// <returns>Collection</returns>
        public Collection UpdateCollection (string collectionId, Collection body)
        {
             spanclient.Client.ApiResponse<Collection> localVarResponse = UpdateCollectionWithHttpInfo(collectionId, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Update collection You must have write access to the collection, ie. you must administer it
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The ID of the collection. This is assigned by the backend.</param>
        /// <param name="body"></param>
        /// <returns>ApiResponse of Collection</returns>
        public spanclient.Client.ApiResponse< Collection > UpdateCollectionWithHttpInfo (string collectionId, Collection body)
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling CollectionsApi->UpdateCollection");

            // verify the required parameter 'body' is set
            if (body == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'body' when calling CollectionsApi->UpdateCollection");

            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = spanclient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = spanclient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter
            localVarRequestOptions.Data = body;

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch< Collection >("/collections/{collectionId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateCollection", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update collection You must have write access to the collection, ie. you must administer it
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The ID of the collection. This is assigned by the backend.</param>
        /// <param name="body"></param>
        /// <returns>Task of Collection</returns>
        public async System.Threading.Tasks.Task<Collection> UpdateCollectionAsync (string collectionId, Collection body)
        {
             spanclient.Client.ApiResponse<Collection> localVarResponse = await UpdateCollectionAsyncWithHttpInfo(collectionId, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Update collection You must have write access to the collection, ie. you must administer it
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId">The ID of the collection. This is assigned by the backend.</param>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (Collection)</returns>
        public async System.Threading.Tasks.Task<spanclient.Client.ApiResponse<Collection>> UpdateCollectionAsyncWithHttpInfo (string collectionId, Collection body)
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling CollectionsApi->UpdateCollection");

            // verify the required parameter 'body' is set
            if (body == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'body' when calling CollectionsApi->UpdateCollection");


            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter
            localVarRequestOptions.Data = body;

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PatchAsync<Collection>("/collections/{collectionId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateCollection", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
