/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using spanclient.Client;
using spanclient.Model;

namespace spanclient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDatadumpApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Data dump
        /// </summary>
        /// <remarks>
        /// Do a complete data dump of your data, devices, outputs and collections.
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>DataDumpResponse</returns>
        DataDumpResponse DataDump (Object body);

        /// <summary>
        /// Data dump
        /// </summary>
        /// <remarks>
        /// Do a complete data dump of your data, devices, outputs and collections.
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of DataDumpResponse</returns>
        ApiResponse<DataDumpResponse> DataDumpWithHttpInfo (Object body);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDatadumpApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Data dump
        /// </summary>
        /// <remarks>
        /// Do a complete data dump of your data, devices, outputs and collections.
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of DataDumpResponse</returns>
        System.Threading.Tasks.Task<DataDumpResponse> DataDumpAsync (Object body);

        /// <summary>
        /// Data dump
        /// </summary>
        /// <remarks>
        /// Do a complete data dump of your data, devices, outputs and collections.
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (DataDumpResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DataDumpResponse>> DataDumpAsyncWithHttpInfo (Object body);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDatadumpApi : IDatadumpApiSync, IDatadumpApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DatadumpApi : IDatadumpApi
    {
        private spanclient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DatadumpApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DatadumpApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DatadumpApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DatadumpApi(String basePath)
        {
            this.Configuration = spanclient.Client.Configuration.MergeConfigurations(
                spanclient.Client.GlobalConfiguration.Instance,
                new spanclient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new spanclient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new spanclient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = spanclient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DatadumpApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DatadumpApi(spanclient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = spanclient.Client.Configuration.MergeConfigurations(
                spanclient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new spanclient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new spanclient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = spanclient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DatadumpApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public DatadumpApi(spanclient.Client.ISynchronousClient client,spanclient.Client.IAsynchronousClient asyncClient, spanclient.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = spanclient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public spanclient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public spanclient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public spanclient.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public spanclient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Data dump Do a complete data dump of your data, devices, outputs and collections.
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>DataDumpResponse</returns>
        public DataDumpResponse DataDump (Object body)
        {
             spanclient.Client.ApiResponse<DataDumpResponse> localVarResponse = DataDumpWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Data dump Do a complete data dump of your data, devices, outputs and collections.
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of DataDumpResponse</returns>
        public spanclient.Client.ApiResponse< DataDumpResponse > DataDumpWithHttpInfo (Object body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'body' when calling DatadumpApi->DataDump");

            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = spanclient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = spanclient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = body;

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post< DataDumpResponse >("/datadump", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DataDump", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Data dump Do a complete data dump of your data, devices, outputs and collections.
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of DataDumpResponse</returns>
        public async System.Threading.Tasks.Task<DataDumpResponse> DataDumpAsync (Object body)
        {
             spanclient.Client.ApiResponse<DataDumpResponse> localVarResponse = await DataDumpAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Data dump Do a complete data dump of your data, devices, outputs and collections.
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (DataDumpResponse)</returns>
        public async System.Threading.Tasks.Task<spanclient.Client.ApiResponse<DataDumpResponse>> DataDumpAsyncWithHttpInfo (Object body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'body' when calling DatadumpApi->DataDump");


            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            localVarRequestOptions.Data = body;

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<DataDumpResponse>("/datadump", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DataDump", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
