/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.0.12 reported-davon
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using spanclient.Client;
using spanclient.Model;

namespace spanclient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOutputsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create output
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="body"></param>
        /// <returns>Output</returns>
        Output CreateOutput (string collectionId, Output body);

        /// <summary>
        /// Create output
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="body"></param>
        /// <returns>ApiResponse of Output</returns>
        ApiResponse<Output> CreateOutputWithHttpInfo (string collectionId, Output body);
        /// <summary>
        /// Delete output
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>Output</returns>
        Output DeleteOutput (string collectionId, string outputId);

        /// <summary>
        /// Delete output
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>ApiResponse of Output</returns>
        ApiResponse<Output> DeleteOutputWithHttpInfo (string collectionId, string outputId);
        /// <summary>
        /// List outputs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <returns>ListOutputResponse</returns>
        ListOutputResponse ListOutputs (string collectionId);

        /// <summary>
        /// List outputs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <returns>ApiResponse of ListOutputResponse</returns>
        ApiResponse<ListOutputResponse> ListOutputsWithHttpInfo (string collectionId);
        /// <summary>
        /// Output logs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>OutputLogs</returns>
        OutputLogs Logs (string collectionId, string outputId);

        /// <summary>
        /// Output logs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>ApiResponse of OutputLogs</returns>
        ApiResponse<OutputLogs> LogsWithHttpInfo (string collectionId, string outputId);
        /// <summary>
        /// Retrieve output
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>Output</returns>
        Output RetrieveOutput (string collectionId, string outputId);

        /// <summary>
        /// Retrieve output
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>ApiResponse of Output</returns>
        ApiResponse<Output> RetrieveOutputWithHttpInfo (string collectionId, string outputId);
        /// <summary>
        /// Output status
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>OutputStatus</returns>
        OutputStatus Status (string collectionId, string outputId);

        /// <summary>
        /// Output status
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>ApiResponse of OutputStatus</returns>
        ApiResponse<OutputStatus> StatusWithHttpInfo (string collectionId, string outputId);
        /// <summary>
        /// Update output
        /// </summary>
        /// <remarks>
        /// Running outputs will be restarted if required. Note that the collection ID can&#39;t be changed on an existing output.
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <param name="body"></param>
        /// <returns>Output</returns>
        Output UpdateOutput (string collectionId, string outputId, Output body);

        /// <summary>
        /// Update output
        /// </summary>
        /// <remarks>
        /// Running outputs will be restarted if required. Note that the collection ID can&#39;t be changed on an existing output.
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <param name="body"></param>
        /// <returns>ApiResponse of Output</returns>
        ApiResponse<Output> UpdateOutputWithHttpInfo (string collectionId, string outputId, Output body);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOutputsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create output
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="body"></param>
        /// <returns>Task of Output</returns>
        System.Threading.Tasks.Task<Output> CreateOutputAsync (string collectionId, Output body);

        /// <summary>
        /// Create output
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (Output)</returns>
        System.Threading.Tasks.Task<ApiResponse<Output>> CreateOutputAsyncWithHttpInfo (string collectionId, Output body);
        /// <summary>
        /// Delete output
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>Task of Output</returns>
        System.Threading.Tasks.Task<Output> DeleteOutputAsync (string collectionId, string outputId);

        /// <summary>
        /// Delete output
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>Task of ApiResponse (Output)</returns>
        System.Threading.Tasks.Task<ApiResponse<Output>> DeleteOutputAsyncWithHttpInfo (string collectionId, string outputId);
        /// <summary>
        /// List outputs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <returns>Task of ListOutputResponse</returns>
        System.Threading.Tasks.Task<ListOutputResponse> ListOutputsAsync (string collectionId);

        /// <summary>
        /// List outputs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <returns>Task of ApiResponse (ListOutputResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListOutputResponse>> ListOutputsAsyncWithHttpInfo (string collectionId);
        /// <summary>
        /// Output logs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>Task of OutputLogs</returns>
        System.Threading.Tasks.Task<OutputLogs> LogsAsync (string collectionId, string outputId);

        /// <summary>
        /// Output logs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>Task of ApiResponse (OutputLogs)</returns>
        System.Threading.Tasks.Task<ApiResponse<OutputLogs>> LogsAsyncWithHttpInfo (string collectionId, string outputId);
        /// <summary>
        /// Retrieve output
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>Task of Output</returns>
        System.Threading.Tasks.Task<Output> RetrieveOutputAsync (string collectionId, string outputId);

        /// <summary>
        /// Retrieve output
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>Task of ApiResponse (Output)</returns>
        System.Threading.Tasks.Task<ApiResponse<Output>> RetrieveOutputAsyncWithHttpInfo (string collectionId, string outputId);
        /// <summary>
        /// Output status
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>Task of OutputStatus</returns>
        System.Threading.Tasks.Task<OutputStatus> StatusAsync (string collectionId, string outputId);

        /// <summary>
        /// Output status
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>Task of ApiResponse (OutputStatus)</returns>
        System.Threading.Tasks.Task<ApiResponse<OutputStatus>> StatusAsyncWithHttpInfo (string collectionId, string outputId);
        /// <summary>
        /// Update output
        /// </summary>
        /// <remarks>
        /// Running outputs will be restarted if required. Note that the collection ID can&#39;t be changed on an existing output.
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <param name="body"></param>
        /// <returns>Task of Output</returns>
        System.Threading.Tasks.Task<Output> UpdateOutputAsync (string collectionId, string outputId, Output body);

        /// <summary>
        /// Update output
        /// </summary>
        /// <remarks>
        /// Running outputs will be restarted if required. Note that the collection ID can&#39;t be changed on an existing output.
        /// </remarks>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (Output)</returns>
        System.Threading.Tasks.Task<ApiResponse<Output>> UpdateOutputAsyncWithHttpInfo (string collectionId, string outputId, Output body);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOutputsApi : IOutputsApiSync, IOutputsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class OutputsApi : IOutputsApi
    {
        private spanclient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="OutputsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public OutputsApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OutputsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public OutputsApi(String basePath)
        {
            this.Configuration = spanclient.Client.Configuration.MergeConfigurations(
                spanclient.Client.GlobalConfiguration.Instance,
                new spanclient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new spanclient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new spanclient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = spanclient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OutputsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public OutputsApi(spanclient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = spanclient.Client.Configuration.MergeConfigurations(
                spanclient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new spanclient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new spanclient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = spanclient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OutputsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public OutputsApi(spanclient.Client.ISynchronousClient client,spanclient.Client.IAsynchronousClient asyncClient, spanclient.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = spanclient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public spanclient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public spanclient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public spanclient.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public spanclient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create output 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="body"></param>
        /// <returns>Output</returns>
        public Output CreateOutput (string collectionId, Output body)
        {
             spanclient.Client.ApiResponse<Output> localVarResponse = CreateOutputWithHttpInfo(collectionId, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create output 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="body"></param>
        /// <returns>ApiResponse of Output</returns>
        public spanclient.Client.ApiResponse< Output > CreateOutputWithHttpInfo (string collectionId, Output body)
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling OutputsApi->CreateOutput");

            // verify the required parameter 'body' is set
            if (body == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'body' when calling OutputsApi->CreateOutput");

            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = spanclient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = spanclient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter
            localVarRequestOptions.Data = body;

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post< Output >("/collections/{collectionId}/outputs", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateOutput", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create output 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="body"></param>
        /// <returns>Task of Output</returns>
        public async System.Threading.Tasks.Task<Output> CreateOutputAsync (string collectionId, Output body)
        {
             spanclient.Client.ApiResponse<Output> localVarResponse = await CreateOutputAsyncWithHttpInfo(collectionId, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create output 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (Output)</returns>
        public async System.Threading.Tasks.Task<spanclient.Client.ApiResponse<Output>> CreateOutputAsyncWithHttpInfo (string collectionId, Output body)
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling OutputsApi->CreateOutput");

            // verify the required parameter 'body' is set
            if (body == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'body' when calling OutputsApi->CreateOutput");


            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter
            localVarRequestOptions.Data = body;

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Output>("/collections/{collectionId}/outputs", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateOutput", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete output 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>Output</returns>
        public Output DeleteOutput (string collectionId, string outputId)
        {
             spanclient.Client.ApiResponse<Output> localVarResponse = DeleteOutputWithHttpInfo(collectionId, outputId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Delete output 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>ApiResponse of Output</returns>
        public spanclient.Client.ApiResponse< Output > DeleteOutputWithHttpInfo (string collectionId, string outputId)
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling OutputsApi->DeleteOutput");

            // verify the required parameter 'outputId' is set
            if (outputId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'outputId' when calling OutputsApi->DeleteOutput");

            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = spanclient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = spanclient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter
            if (outputId != null)
                localVarRequestOptions.PathParameters.Add("outputId", spanclient.Client.ClientUtils.ParameterToString(outputId)); // path parameter

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete< Output >("/collections/{collectionId}/outputs/{outputId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteOutput", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete output 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>Task of Output</returns>
        public async System.Threading.Tasks.Task<Output> DeleteOutputAsync (string collectionId, string outputId)
        {
             spanclient.Client.ApiResponse<Output> localVarResponse = await DeleteOutputAsyncWithHttpInfo(collectionId, outputId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Delete output 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>Task of ApiResponse (Output)</returns>
        public async System.Threading.Tasks.Task<spanclient.Client.ApiResponse<Output>> DeleteOutputAsyncWithHttpInfo (string collectionId, string outputId)
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling OutputsApi->DeleteOutput");

            // verify the required parameter 'outputId' is set
            if (outputId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'outputId' when calling OutputsApi->DeleteOutput");


            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter
            if (outputId != null)
                localVarRequestOptions.PathParameters.Add("outputId", spanclient.Client.ClientUtils.ParameterToString(outputId)); // path parameter

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Output>("/collections/{collectionId}/outputs/{outputId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteOutput", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List outputs 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <returns>ListOutputResponse</returns>
        public ListOutputResponse ListOutputs (string collectionId)
        {
             spanclient.Client.ApiResponse<ListOutputResponse> localVarResponse = ListOutputsWithHttpInfo(collectionId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// List outputs 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <returns>ApiResponse of ListOutputResponse</returns>
        public spanclient.Client.ApiResponse< ListOutputResponse > ListOutputsWithHttpInfo (string collectionId)
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling OutputsApi->ListOutputs");

            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = spanclient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = spanclient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get< ListOutputResponse >("/collections/{collectionId}/outputs", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListOutputs", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List outputs 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <returns>Task of ListOutputResponse</returns>
        public async System.Threading.Tasks.Task<ListOutputResponse> ListOutputsAsync (string collectionId)
        {
             spanclient.Client.ApiResponse<ListOutputResponse> localVarResponse = await ListOutputsAsyncWithHttpInfo(collectionId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// List outputs 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <returns>Task of ApiResponse (ListOutputResponse)</returns>
        public async System.Threading.Tasks.Task<spanclient.Client.ApiResponse<ListOutputResponse>> ListOutputsAsyncWithHttpInfo (string collectionId)
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling OutputsApi->ListOutputs");


            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListOutputResponse>("/collections/{collectionId}/outputs", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListOutputs", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Output logs 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>OutputLogs</returns>
        public OutputLogs Logs (string collectionId, string outputId)
        {
             spanclient.Client.ApiResponse<OutputLogs> localVarResponse = LogsWithHttpInfo(collectionId, outputId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Output logs 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>ApiResponse of OutputLogs</returns>
        public spanclient.Client.ApiResponse< OutputLogs > LogsWithHttpInfo (string collectionId, string outputId)
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling OutputsApi->Logs");

            // verify the required parameter 'outputId' is set
            if (outputId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'outputId' when calling OutputsApi->Logs");

            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = spanclient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = spanclient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter
            if (outputId != null)
                localVarRequestOptions.PathParameters.Add("outputId", spanclient.Client.ClientUtils.ParameterToString(outputId)); // path parameter

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get< OutputLogs >("/collections/{collectionId}/outputs/{outputId}/logs", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Logs", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Output logs 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>Task of OutputLogs</returns>
        public async System.Threading.Tasks.Task<OutputLogs> LogsAsync (string collectionId, string outputId)
        {
             spanclient.Client.ApiResponse<OutputLogs> localVarResponse = await LogsAsyncWithHttpInfo(collectionId, outputId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Output logs 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>Task of ApiResponse (OutputLogs)</returns>
        public async System.Threading.Tasks.Task<spanclient.Client.ApiResponse<OutputLogs>> LogsAsyncWithHttpInfo (string collectionId, string outputId)
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling OutputsApi->Logs");

            // verify the required parameter 'outputId' is set
            if (outputId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'outputId' when calling OutputsApi->Logs");


            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter
            if (outputId != null)
                localVarRequestOptions.PathParameters.Add("outputId", spanclient.Client.ClientUtils.ParameterToString(outputId)); // path parameter

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<OutputLogs>("/collections/{collectionId}/outputs/{outputId}/logs", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Logs", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve output 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>Output</returns>
        public Output RetrieveOutput (string collectionId, string outputId)
        {
             spanclient.Client.ApiResponse<Output> localVarResponse = RetrieveOutputWithHttpInfo(collectionId, outputId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve output 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>ApiResponse of Output</returns>
        public spanclient.Client.ApiResponse< Output > RetrieveOutputWithHttpInfo (string collectionId, string outputId)
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling OutputsApi->RetrieveOutput");

            // verify the required parameter 'outputId' is set
            if (outputId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'outputId' when calling OutputsApi->RetrieveOutput");

            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = spanclient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = spanclient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter
            if (outputId != null)
                localVarRequestOptions.PathParameters.Add("outputId", spanclient.Client.ClientUtils.ParameterToString(outputId)); // path parameter

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get< Output >("/collections/{collectionId}/outputs/{outputId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RetrieveOutput", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve output 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>Task of Output</returns>
        public async System.Threading.Tasks.Task<Output> RetrieveOutputAsync (string collectionId, string outputId)
        {
             spanclient.Client.ApiResponse<Output> localVarResponse = await RetrieveOutputAsyncWithHttpInfo(collectionId, outputId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieve output 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>Task of ApiResponse (Output)</returns>
        public async System.Threading.Tasks.Task<spanclient.Client.ApiResponse<Output>> RetrieveOutputAsyncWithHttpInfo (string collectionId, string outputId)
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling OutputsApi->RetrieveOutput");

            // verify the required parameter 'outputId' is set
            if (outputId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'outputId' when calling OutputsApi->RetrieveOutput");


            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter
            if (outputId != null)
                localVarRequestOptions.PathParameters.Add("outputId", spanclient.Client.ClientUtils.ParameterToString(outputId)); // path parameter

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Output>("/collections/{collectionId}/outputs/{outputId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RetrieveOutput", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Output status 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>OutputStatus</returns>
        public OutputStatus Status (string collectionId, string outputId)
        {
             spanclient.Client.ApiResponse<OutputStatus> localVarResponse = StatusWithHttpInfo(collectionId, outputId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Output status 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>ApiResponse of OutputStatus</returns>
        public spanclient.Client.ApiResponse< OutputStatus > StatusWithHttpInfo (string collectionId, string outputId)
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling OutputsApi->Status");

            // verify the required parameter 'outputId' is set
            if (outputId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'outputId' when calling OutputsApi->Status");

            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = spanclient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = spanclient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter
            if (outputId != null)
                localVarRequestOptions.PathParameters.Add("outputId", spanclient.Client.ClientUtils.ParameterToString(outputId)); // path parameter

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get< OutputStatus >("/collections/{collectionId}/outputs/{outputId}/status", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Status", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Output status 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>Task of OutputStatus</returns>
        public async System.Threading.Tasks.Task<OutputStatus> StatusAsync (string collectionId, string outputId)
        {
             spanclient.Client.ApiResponse<OutputStatus> localVarResponse = await StatusAsyncWithHttpInfo(collectionId, outputId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Output status 
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <returns>Task of ApiResponse (OutputStatus)</returns>
        public async System.Threading.Tasks.Task<spanclient.Client.ApiResponse<OutputStatus>> StatusAsyncWithHttpInfo (string collectionId, string outputId)
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling OutputsApi->Status");

            // verify the required parameter 'outputId' is set
            if (outputId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'outputId' when calling OutputsApi->Status");


            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter
            if (outputId != null)
                localVarRequestOptions.PathParameters.Add("outputId", spanclient.Client.ClientUtils.ParameterToString(outputId)); // path parameter

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<OutputStatus>("/collections/{collectionId}/outputs/{outputId}/status", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Status", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update output Running outputs will be restarted if required. Note that the collection ID can&#39;t be changed on an existing output.
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <param name="body"></param>
        /// <returns>Output</returns>
        public Output UpdateOutput (string collectionId, string outputId, Output body)
        {
             spanclient.Client.ApiResponse<Output> localVarResponse = UpdateOutputWithHttpInfo(collectionId, outputId, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Update output Running outputs will be restarted if required. Note that the collection ID can&#39;t be changed on an existing output.
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <param name="body"></param>
        /// <returns>ApiResponse of Output</returns>
        public spanclient.Client.ApiResponse< Output > UpdateOutputWithHttpInfo (string collectionId, string outputId, Output body)
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling OutputsApi->UpdateOutput");

            // verify the required parameter 'outputId' is set
            if (outputId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'outputId' when calling OutputsApi->UpdateOutput");

            // verify the required parameter 'body' is set
            if (body == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'body' when calling OutputsApi->UpdateOutput");

            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = spanclient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = spanclient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter
            if (outputId != null)
                localVarRequestOptions.PathParameters.Add("outputId", spanclient.Client.ClientUtils.ParameterToString(outputId)); // path parameter
            localVarRequestOptions.Data = body;

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch< Output >("/collections/{collectionId}/outputs/{outputId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateOutput", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update output Running outputs will be restarted if required. Note that the collection ID can&#39;t be changed on an existing output.
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <param name="body"></param>
        /// <returns>Task of Output</returns>
        public async System.Threading.Tasks.Task<Output> UpdateOutputAsync (string collectionId, string outputId, Output body)
        {
             spanclient.Client.ApiResponse<Output> localVarResponse = await UpdateOutputAsyncWithHttpInfo(collectionId, outputId, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Update output Running outputs will be restarted if required. Note that the collection ID can&#39;t be changed on an existing output.
        /// </summary>
        /// <exception cref="spanclient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="collectionId"></param>
        /// <param name="outputId"></param>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (Output)</returns>
        public async System.Threading.Tasks.Task<spanclient.Client.ApiResponse<Output>> UpdateOutputAsyncWithHttpInfo (string collectionId, string outputId, Output body)
        {
            // verify the required parameter 'collectionId' is set
            if (collectionId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'collectionId' when calling OutputsApi->UpdateOutput");

            // verify the required parameter 'outputId' is set
            if (outputId == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'outputId' when calling OutputsApi->UpdateOutput");

            // verify the required parameter 'body' is set
            if (body == null)
                throw new spanclient.Client.ApiException(400, "Missing required parameter 'body' when calling OutputsApi->UpdateOutput");


            spanclient.Client.RequestOptions localVarRequestOptions = new spanclient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (collectionId != null)
                localVarRequestOptions.PathParameters.Add("collectionId", spanclient.Client.ClientUtils.ParameterToString(collectionId)); // path parameter
            if (outputId != null)
                localVarRequestOptions.PathParameters.Add("outputId", spanclient.Client.ClientUtils.ParameterToString(outputId)); // path parameter
            localVarRequestOptions.Data = body;

            // authentication (APIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Token", this.Configuration.GetApiKeyWithPrefix("X-API-Token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PatchAsync<Output>("/collections/{collectionId}/outputs/{outputId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateOutput", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
