/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.0.12 reported-davon
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using spanclient.Api;
using spanclient.Model;
using spanclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing CoAPMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CoAPMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CoAPMetadata
        //private CoAPMetadata instance;

        public CoAPMetadataTests()
        {
            // TODO uncomment below to create an instance of CoAPMetadata
            //instance = new CoAPMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CoAPMetadata
        /// </summary>
        [Fact]
        public void CoAPMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CoAPMetadata
            //Assert.IsInstanceOfType<CoAPMetadata> (instance, "variable 'instance' is a CoAPMetadata");
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

    }

}
