/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using spanclient.Api;
using spanclient.Model;
using spanclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing CollectionFirmware
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CollectionFirmwareTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CollectionFirmware
        //private CollectionFirmware instance;

        public CollectionFirmwareTests()
        {
            // TODO uncomment below to create an instance of CollectionFirmware
            //instance = new CollectionFirmware();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CollectionFirmware
        /// </summary>
        [Fact]
        public void CollectionFirmwareInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CollectionFirmware
            //Assert.IsInstanceOfType<CollectionFirmware> (instance, "variable 'instance' is a CollectionFirmware");
        }


        /// <summary>
        /// Test the property 'CurrentFirmwareId'
        /// </summary>
        [Fact]
        public void CurrentFirmwareIdTest()
        {
            // TODO unit test for the property 'CurrentFirmwareId'
        }
        /// <summary>
        /// Test the property 'TargetFirmwareId'
        /// </summary>
        [Fact]
        public void TargetFirmwareIdTest()
        {
            // TODO unit test for the property 'TargetFirmwareId'
        }
        /// <summary>
        /// Test the property 'Management'
        /// </summary>
        [Fact]
        public void ManagementTest()
        {
            // TODO unit test for the property 'Management'
        }

    }

}
