/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.0.12 reported-davon
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using spanclient.Api;
using spanclient.Model;
using spanclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing CollectionFirmwareFirmwareManagement
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CollectionFirmwareFirmwareManagementTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CollectionFirmwareFirmwareManagement
        //private CollectionFirmwareFirmwareManagement instance;

        public CollectionFirmwareFirmwareManagementTests()
        {
            // TODO uncomment below to create an instance of CollectionFirmwareFirmwareManagement
            //instance = new CollectionFirmwareFirmwareManagement();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CollectionFirmwareFirmwareManagement
        /// </summary>
        [Fact]
        public void CollectionFirmwareFirmwareManagementInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CollectionFirmwareFirmwareManagement
            //Assert.IsInstanceOfType<CollectionFirmwareFirmwareManagement> (instance, "variable 'instance' is a CollectionFirmwareFirmwareManagement");
        }



    }

}
