/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using spanclient.Api;
using spanclient.Model;
using spanclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing DataDumpResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataDumpResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataDumpResponse
        //private DataDumpResponse instance;

        public DataDumpResponseTests()
        {
            // TODO uncomment below to create an instance of DataDumpResponse
            //instance = new DataDumpResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataDumpResponse
        /// </summary>
        [Fact]
        public void DataDumpResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DataDumpResponse
            //Assert.IsInstanceOfType<DataDumpResponse> (instance, "variable 'instance' is a DataDumpResponse");
        }


        /// <summary>
        /// Test the property 'Collections'
        /// </summary>
        [Fact]
        public void CollectionsTest()
        {
            // TODO unit test for the property 'Collections'
        }

    }

}
