/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using spanclient.Api;
using spanclient.Model;
using spanclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing DumpedCollection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DumpedCollectionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DumpedCollection
        //private DumpedCollection instance;

        public DumpedCollectionTests()
        {
            // TODO uncomment below to create an instance of DumpedCollection
            //instance = new DumpedCollection();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DumpedCollection
        /// </summary>
        [Fact]
        public void DumpedCollectionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DumpedCollection
            //Assert.IsInstanceOfType<DumpedCollection> (instance, "variable 'instance' is a DumpedCollection");
        }


        /// <summary>
        /// Test the property 'Collection'
        /// </summary>
        [Fact]
        public void CollectionTest()
        {
            // TODO unit test for the property 'Collection'
        }
        /// <summary>
        /// Test the property 'Devices'
        /// </summary>
        [Fact]
        public void DevicesTest()
        {
            // TODO unit test for the property 'Devices'
        }
        /// <summary>
        /// Test the property 'Outputs'
        /// </summary>
        [Fact]
        public void OutputsTest()
        {
            // TODO unit test for the property 'Outputs'
        }

    }

}
