/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using spanclient.Api;
using spanclient.Model;
using spanclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing DumpedDevice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DumpedDeviceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DumpedDevice
        //private DumpedDevice instance;

        public DumpedDeviceTests()
        {
            // TODO uncomment below to create an instance of DumpedDevice
            //instance = new DumpedDevice();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DumpedDevice
        /// </summary>
        [Fact]
        public void DumpedDeviceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DumpedDevice
            //Assert.IsInstanceOfType<DumpedDevice> (instance, "variable 'instance' is a DumpedDevice");
        }


        /// <summary>
        /// Test the property 'Device'
        /// </summary>
        [Fact]
        public void DeviceTest()
        {
            // TODO unit test for the property 'Device'
        }

    }

}
