/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.0.12 reported-davon
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using spanclient.Api;
using spanclient.Model;
using spanclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing FieldMask
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FieldMaskTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FieldMask
        //private FieldMask instance;

        public FieldMaskTests()
        {
            // TODO uncomment below to create an instance of FieldMask
            //instance = new FieldMask();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FieldMask
        /// </summary>
        [Fact]
        public void FieldMaskInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FieldMask
            //Assert.IsInstanceOfType<FieldMask> (instance, "variable 'instance' is a FieldMask");
        }


        /// <summary>
        /// Test the property 'Imsi'
        /// </summary>
        [Fact]
        public void ImsiTest()
        {
            // TODO unit test for the property 'Imsi'
        }
        /// <summary>
        /// Test the property 'Imei'
        /// </summary>
        [Fact]
        public void ImeiTest()
        {
            // TODO unit test for the property 'Imei'
        }
        /// <summary>
        /// Test the property 'Msisdn'
        /// </summary>
        [Fact]
        public void MsisdnTest()
        {
            // TODO unit test for the property 'Msisdn'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }

    }

}
