/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.0.12 reported-davon
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using spanclient.Api;
using spanclient.Model;
using spanclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing FirmwareMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FirmwareMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FirmwareMetadata
        //private FirmwareMetadata instance;

        public FirmwareMetadataTests()
        {
            // TODO uncomment below to create an instance of FirmwareMetadata
            //instance = new FirmwareMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FirmwareMetadata
        /// </summary>
        [Fact]
        public void FirmwareMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FirmwareMetadata
            //Assert.IsInstanceOfType<FirmwareMetadata> (instance, "variable 'instance' is a FirmwareMetadata");
        }


        /// <summary>
        /// Test the property 'CurrentFirmwareId'
        /// </summary>
        [Fact]
        public void CurrentFirmwareIdTest()
        {
            // TODO unit test for the property 'CurrentFirmwareId'
        }
        /// <summary>
        /// Test the property 'TargetFirmwareId'
        /// </summary>
        [Fact]
        public void TargetFirmwareIdTest()
        {
            // TODO unit test for the property 'TargetFirmwareId'
        }
        /// <summary>
        /// Test the property 'FirmwareVersion'
        /// </summary>
        [Fact]
        public void FirmwareVersionTest()
        {
            // TODO unit test for the property 'FirmwareVersion'
        }
        /// <summary>
        /// Test the property 'SerialNumber'
        /// </summary>
        [Fact]
        public void SerialNumberTest()
        {
            // TODO unit test for the property 'SerialNumber'
        }
        /// <summary>
        /// Test the property 'ModelNumber'
        /// </summary>
        [Fact]
        public void ModelNumberTest()
        {
            // TODO unit test for the property 'ModelNumber'
        }
        /// <summary>
        /// Test the property 'Manufacturer'
        /// </summary>
        [Fact]
        public void ManufacturerTest()
        {
            // TODO unit test for the property 'Manufacturer'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'StateMessage'
        /// </summary>
        [Fact]
        public void StateMessageTest()
        {
            // TODO unit test for the property 'StateMessage'
        }

    }

}
