/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.0.12 reported-davon
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using spanclient.Api;
using spanclient.Model;
using spanclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing FirmwareUsageResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FirmwareUsageResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FirmwareUsageResponse
        //private FirmwareUsageResponse instance;

        public FirmwareUsageResponseTests()
        {
            // TODO uncomment below to create an instance of FirmwareUsageResponse
            //instance = new FirmwareUsageResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FirmwareUsageResponse
        /// </summary>
        [Fact]
        public void FirmwareUsageResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FirmwareUsageResponse
            //Assert.IsInstanceOfType<FirmwareUsageResponse> (instance, "variable 'instance' is a FirmwareUsageResponse");
        }


        /// <summary>
        /// Test the property 'ImageId'
        /// </summary>
        [Fact]
        public void ImageIdTest()
        {
            // TODO unit test for the property 'ImageId'
        }
        /// <summary>
        /// Test the property 'Targeted'
        /// </summary>
        [Fact]
        public void TargetedTest()
        {
            // TODO unit test for the property 'Targeted'
        }
        /// <summary>
        /// Test the property 'Current'
        /// </summary>
        [Fact]
        public void CurrentTest()
        {
            // TODO unit test for the property 'Current'
        }

    }

}
