/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using spanclient.Api;
using spanclient.Model;
using spanclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing ListDataResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListDataResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListDataResponse
        //private ListDataResponse instance;

        public ListDataResponseTests()
        {
            // TODO uncomment below to create an instance of ListDataResponse
            //instance = new ListDataResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListDataResponse
        /// </summary>
        [Fact]
        public void ListDataResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ListDataResponse
            //Assert.IsInstanceOfType<ListDataResponse> (instance, "variable 'instance' is a ListDataResponse");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
