/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.0.12 reported-davon
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using spanclient.Api;
using spanclient.Model;
using spanclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing ListDevicesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListDevicesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListDevicesResponse
        //private ListDevicesResponse instance;

        public ListDevicesResponseTests()
        {
            // TODO uncomment below to create an instance of ListDevicesResponse
            //instance = new ListDevicesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListDevicesResponse
        /// </summary>
        [Fact]
        public void ListDevicesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ListDevicesResponse
            //Assert.IsInstanceOfType<ListDevicesResponse> (instance, "variable 'instance' is a ListDevicesResponse");
        }


        /// <summary>
        /// Test the property 'Devices'
        /// </summary>
        [Fact]
        public void DevicesTest()
        {
            // TODO unit test for the property 'Devices'
        }

    }

}
