/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.0.12 reported-davon
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using spanclient.Api;
using spanclient.Model;
using spanclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing ListFirmwareResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListFirmwareResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListFirmwareResponse
        //private ListFirmwareResponse instance;

        public ListFirmwareResponseTests()
        {
            // TODO uncomment below to create an instance of ListFirmwareResponse
            //instance = new ListFirmwareResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListFirmwareResponse
        /// </summary>
        [Fact]
        public void ListFirmwareResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ListFirmwareResponse
            //Assert.IsInstanceOfType<ListFirmwareResponse> (instance, "variable 'instance' is a ListFirmwareResponse");
        }


        /// <summary>
        /// Test the property 'Images'
        /// </summary>
        [Fact]
        public void ImagesTest()
        {
            // TODO unit test for the property 'Images'
        }

    }

}
