/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.0.12 reported-davon
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using spanclient.Api;
using spanclient.Model;
using spanclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing MultiSendMessageResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MultiSendMessageResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MultiSendMessageResponse
        //private MultiSendMessageResponse instance;

        public MultiSendMessageResponseTests()
        {
            // TODO uncomment below to create an instance of MultiSendMessageResponse
            //instance = new MultiSendMessageResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MultiSendMessageResponse
        /// </summary>
        [Fact]
        public void MultiSendMessageResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MultiSendMessageResponse
            //Assert.IsInstanceOfType<MultiSendMessageResponse> (instance, "variable 'instance' is a MultiSendMessageResponse");
        }


        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'Sent'
        /// </summary>
        [Fact]
        public void SentTest()
        {
            // TODO unit test for the property 'Sent'
        }
        /// <summary>
        /// Test the property 'Failed'
        /// </summary>
        [Fact]
        public void FailedTest()
        {
            // TODO unit test for the property 'Failed'
        }

    }

}
