/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using spanclient.Api;
using spanclient.Model;
using spanclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing OutputLogEntry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OutputLogEntryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OutputLogEntry
        //private OutputLogEntry instance;

        public OutputLogEntryTests()
        {
            // TODO uncomment below to create an instance of OutputLogEntry
            //instance = new OutputLogEntry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OutputLogEntry
        /// </summary>
        [Fact]
        public void OutputLogEntryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OutputLogEntry
            //Assert.IsInstanceOfType<OutputLogEntry> (instance, "variable 'instance' is a OutputLogEntry");
        }


        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Fact]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Repeated'
        /// </summary>
        [Fact]
        public void RepeatedTest()
        {
            // TODO unit test for the property 'Repeated'
        }

    }

}
