/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using spanclient.Api;
using spanclient.Model;
using spanclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing OutputLogs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OutputLogsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OutputLogs
        //private OutputLogs instance;

        public OutputLogsTests()
        {
            // TODO uncomment below to create an instance of OutputLogs
            //instance = new OutputLogs();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OutputLogs
        /// </summary>
        [Fact]
        public void OutputLogsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OutputLogs
            //Assert.IsInstanceOfType<OutputLogs> (instance, "variable 'instance' is a OutputLogs");
        }


        /// <summary>
        /// Test the property 'Logs'
        /// </summary>
        [Fact]
        public void LogsTest()
        {
            // TODO unit test for the property 'Logs'
        }

    }

}
