/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using spanclient.Api;
using spanclient.Model;
using spanclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing OutputStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OutputStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OutputStatus
        //private OutputStatus instance;

        public OutputStatusTests()
        {
            // TODO uncomment below to create an instance of OutputStatus
            //instance = new OutputStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OutputStatus
        /// </summary>
        [Fact]
        public void OutputStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OutputStatus
            //Assert.IsInstanceOfType<OutputStatus> (instance, "variable 'instance' is a OutputStatus");
        }


        /// <summary>
        /// Test the property 'CollectionId'
        /// </summary>
        [Fact]
        public void CollectionIdTest()
        {
            // TODO unit test for the property 'CollectionId'
        }
        /// <summary>
        /// Test the property 'OutputId'
        /// </summary>
        [Fact]
        public void OutputIdTest()
        {
            // TODO unit test for the property 'OutputId'
        }
        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
        /// <summary>
        /// Test the property 'ErrorCount'
        /// </summary>
        [Fact]
        public void ErrorCountTest()
        {
            // TODO unit test for the property 'ErrorCount'
        }
        /// <summary>
        /// Test the property 'Forwarded'
        /// </summary>
        [Fact]
        public void ForwardedTest()
        {
            // TODO unit test for the property 'Forwarded'
        }
        /// <summary>
        /// Test the property 'Received'
        /// </summary>
        [Fact]
        public void ReceivedTest()
        {
            // TODO unit test for the property 'Received'
        }
        /// <summary>
        /// Test the property 'Retransmits'
        /// </summary>
        [Fact]
        public void RetransmitsTest()
        {
            // TODO unit test for the property 'Retransmits'
        }

    }

}
