/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using spanclient.Api;
using spanclient.Model;
using spanclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing OutputDataMessageOutputMessageType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OutputDataMessageOutputMessageTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OutputDataMessageOutputMessageType
        //private OutputDataMessageOutputMessageType instance;

        public OutputDataMessageOutputMessageTypeTests()
        {
            // TODO uncomment below to create an instance of OutputDataMessageOutputMessageType
            //instance = new OutputDataMessageOutputMessageType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OutputDataMessageOutputMessageType
        /// </summary>
        [Fact]
        public void OutputDataMessageOutputMessageTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OutputDataMessageOutputMessageType
            //Assert.IsInstanceOfType<OutputDataMessageOutputMessageType> (instance, "variable 'instance' is a OutputDataMessageOutputMessageType");
        }



    }

}
