/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.0.12 reported-davon
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using spanclient.Api;
using spanclient.Model;
using spanclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing OutputDataMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OutputDataMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OutputDataMessage
        //private OutputDataMessage instance;

        public OutputDataMessageTests()
        {
            // TODO uncomment below to create an instance of OutputDataMessage
            //instance = new OutputDataMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OutputDataMessage
        /// </summary>
        [Fact]
        public void OutputDataMessageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OutputDataMessage
            //Assert.IsInstanceOfType<OutputDataMessage> (instance, "variable 'instance' is a OutputDataMessage");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Device'
        /// </summary>
        [Fact]
        public void DeviceTest()
        {
            // TODO unit test for the property 'Device'
        }
        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }
        /// <summary>
        /// Test the property 'Received'
        /// </summary>
        [Fact]
        public void ReceivedTest()
        {
            // TODO unit test for the property 'Received'
        }
        /// <summary>
        /// Test the property 'Transport'
        /// </summary>
        [Fact]
        public void TransportTest()
        {
            // TODO unit test for the property 'Transport'
        }
        /// <summary>
        /// Test the property 'UdpMetaData'
        /// </summary>
        [Fact]
        public void UdpMetaDataTest()
        {
            // TODO unit test for the property 'UdpMetaData'
        }
        /// <summary>
        /// Test the property 'CoapMetaData'
        /// </summary>
        [Fact]
        public void CoapMetaDataTest()
        {
            // TODO unit test for the property 'CoapMetaData'
        }

    }

}
