/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using spanclient.Api;
using spanclient.Model;
using spanclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing ProtobufAny
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProtobufAnyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProtobufAny
        //private ProtobufAny instance;

        public ProtobufAnyTests()
        {
            // TODO uncomment below to create an instance of ProtobufAny
            //instance = new ProtobufAny();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProtobufAny
        /// </summary>
        [Fact]
        public void ProtobufAnyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProtobufAny
            //Assert.IsInstanceOfType<ProtobufAny> (instance, "variable 'instance' is a ProtobufAny");
        }


        /// <summary>
        /// Test the property 'TypeUrl'
        /// </summary>
        [Fact]
        public void TypeUrlTest()
        {
            // TODO unit test for the property 'TypeUrl'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
