/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using spanclient.Api;
using spanclient.Model;
using spanclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing RuntimeError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RuntimeErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RuntimeError
        //private RuntimeError instance;

        public RuntimeErrorTests()
        {
            // TODO uncomment below to create an instance of RuntimeError
            //instance = new RuntimeError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RuntimeError
        /// </summary>
        [Fact]
        public void RuntimeErrorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RuntimeError
            //Assert.IsInstanceOfType<RuntimeError> (instance, "variable 'instance' is a RuntimeError");
        }


        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Fact]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }

    }

}
