/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.0.12 reported-davon
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using spanclient.Api;
using spanclient.Model;
using spanclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing UDPMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UDPMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UDPMetadata
        //private UDPMetadata instance;

        public UDPMetadataTests()
        {
            // TODO uncomment below to create an instance of UDPMetadata
            //instance = new UDPMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UDPMetadata
        /// </summary>
        [Fact]
        public void UDPMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UDPMetadata
            //Assert.IsInstanceOfType<UDPMetadata> (instance, "variable 'instance' is a UDPMetadata");
        }


        /// <summary>
        /// Test the property 'LocalPort'
        /// </summary>
        [Fact]
        public void LocalPortTest()
        {
            // TODO unit test for the property 'LocalPort'
        }
        /// <summary>
        /// Test the property 'RemotePort'
        /// </summary>
        [Fact]
        public void RemotePortTest()
        {
            // TODO unit test for the property 'RemotePort'
        }

    }

}
