/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.0.12 reported-davon
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using spanclient.Api;
using spanclient.Model;
using spanclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace spanclient.Test
{
    /// <summary>
    ///  Class for testing UpdateDeviceRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateDeviceRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateDeviceRequest
        //private UpdateDeviceRequest instance;

        public UpdateDeviceRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateDeviceRequest
            //instance = new UpdateDeviceRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateDeviceRequest
        /// </summary>
        [Fact]
        public void UpdateDeviceRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateDeviceRequest
            //Assert.IsInstanceOfType<UpdateDeviceRequest> (instance, "variable 'instance' is a UpdateDeviceRequest");
        }


        /// <summary>
        /// Test the property 'ExistingCollectionId'
        /// </summary>
        [Fact]
        public void ExistingCollectionIdTest()
        {
            // TODO unit test for the property 'ExistingCollectionId'
        }
        /// <summary>
        /// Test the property 'DeviceId'
        /// </summary>
        [Fact]
        public void DeviceIdTest()
        {
            // TODO unit test for the property 'DeviceId'
        }
        /// <summary>
        /// Test the property 'CollectionId'
        /// </summary>
        [Fact]
        public void CollectionIdTest()
        {
            // TODO unit test for the property 'CollectionId'
        }
        /// <summary>
        /// Test the property 'Imsi'
        /// </summary>
        [Fact]
        public void ImsiTest()
        {
            // TODO unit test for the property 'Imsi'
        }
        /// <summary>
        /// Test the property 'Imei'
        /// </summary>
        [Fact]
        public void ImeiTest()
        {
            // TODO unit test for the property 'Imei'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Firmware'
        /// </summary>
        [Fact]
        public void FirmwareTest()
        {
            // TODO unit test for the property 'Firmware'
        }

    }

}
