/* 
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.0.12 reported-davon
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = spanclient.Client.OpenAPIDateConverter;

namespace spanclient.Model
{
    /// <summary>
    /// The firmware management settings for a collection can either be \&quot;disabled\&quot;, ie there is no firmware management for this collection, \&quot;collection\&quot;; devices are managed through the settings on the collection or \&quot;device\&quot; where each device is configured individual.
    /// </summary>
    /// <value>The firmware management settings for a collection can either be \&quot;disabled\&quot;, ie there is no firmware management for this collection, \&quot;collection\&quot;; devices are managed through the settings on the collection or \&quot;device\&quot; where each device is configured individual.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum CollectionFirmwareFirmwareManagement
    {
        /// <summary>
        /// Enum Unspecified for value: unspecified
        /// </summary>
        [EnumMember(Value = "unspecified")]
        Unspecified = 1,

        /// <summary>
        /// Enum Disabled for value: disabled
        /// </summary>
        [EnumMember(Value = "disabled")]
        Disabled = 2,

        /// <summary>
        /// Enum Collection for value: collection
        /// </summary>
        [EnumMember(Value = "collection")]
        Collection = 3,

        /// <summary>
        /// Enum Device for value: device
        /// </summary>
        [EnumMember(Value = "device")]
        Device = 4

    }

}
